language: node_js
node_js:
  - '6'
  - '5'

cache:
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email: false

install:
  - npm install

script:
  - npm run test
